META:
  EXPERIMENT_NAME: 'baseline'
  USER: 'Moritz'


SETUP:
  DEVICE: 0
  LOGLEVEL: 'INFO'
  MODEL: 'UNet'
  DATASET: 'EMPIRE10'
  TASK: 'SEG'
  TRAIN: True
  TEST: False
  TRAIN_TEST: False
  SPLIT: 0.3


HYPERPARAMETERS:
  LEARNING_RATE: 0.01
  BATCH_SIZE: 1
  EPOCHS: 15
  EVAL_EVERY: 2
